### ISSUE TITLE
Refreshing on Production Build leads to timeout

### ISSUE THREAD

**Issue by joshwcorbett** [jnt0r/vue-auth0-plugin#330] opened 2022-01-04 19:12 UTC
### Preface
I'd like to preface this issue with a warm thank you for building this plugin, it's been very convenient for me.

### Overview
Upon refreshing or revisiting a page on a production build, the page layout is present but no pages actually render inside of `<router-view />` and no navigation item will highlight. The page becomes completely unusable and barren, clicking on router links or entering a new url into the url bar does nothing. After maybe 10 minutes does the page finally load its contents. I suspect this has something to do with the `beforeEnter: AuthenticationGuard` on the router, but this is not for certain.
<br />
Source: Chrome Dev Tools
<img width="389" alt="Screen Shot 2022-01-04 at 12 10 49 PM" src="https://user-images.githubusercontent.com/23065423/148111302-6cfb2dcd-b5a9-4c26-95cf-eece4f956797.png">
Source: Sentry.io
<img width="859" alt="Screen Shot 2022-01-04 at 12 11 58 PM" src="https://user-images.githubusercontent.com/23065423/148111424-740d3028-a7af-4701-9d44-14056b8c200a.png">

### Workaround
There is a workaround thankfully, clear all cookies stored by auth0 or this plugin. User will be greeted by a login screen where they can once again login and the app will magically work again.

### To Reproduce
1. Create a vue project with vite;
2. Use the `AuthenticationGaurd` from `vue-auth0-plugin` on all routes inside vue router configuration;
3. Build and serve project over localhost;
4. After logging in, refresh the page.

### Closing
Thanks again, and I hope this issue gets fixed before I have to move to move away from this plugin and manually integrate auth0 into my application.

**Comment by jnt0r** [comment] 2022-01-09 07:53
Hey @joshwcorbett, thanks for your feedback and for your issue. I will take a look at the issue you described.

**Comment by jnt0r** [comment] 2022-01-09 14:16
I was not able to reproduce your error. Do you have a sample repository or a codepen?
Does it only appear on production builds (vue-cli-service build) or also on development builds (vue-cli-service serve --https)?

**Comment by jnt0r** [comment] 2022-02-01 17:17
Hey @joshwcorbett, still got this error? Otherwise, I would close this issue.

**Closed** 2022-02-15 16:43 UTC
